package baliviya.com.github.eduBot.entity.enums;

public enum WaitingType {

    START,
    SET_FULL_NAME, SET_PHONE_NUMBER,  // id003_Registration
    CHOICE_CATEGORY, HANDLING_TEXT, // id004_Task
    CHOICE_RECEPTION, SET_QUESTION,
    WAIT, EVENT_SELECTION, EVENT,
    QUEST,
    START_DATE, END_DATE,
    CHOICE_OPTION,
    SET_TEXT, SET_TEXT_SURVEY_KZ,
    DONE, CHOICE_APPEAL, BACK_BUTTON_IN_MENU,
    CHOOSE_EVENT, NEW_EVENT, SET_PHOTO, SET_TEXT_EVENT, CHOOSE_OPTION, DONE_BUTTON, COMMAND_EDITOR, NEXT_KEYBOARD, UPDATE_BUTTON, UPDATE_TEXT, UPDATE_FILE, UPDATE_BUTTON_LINK, WAIT_TO_UPLOAD_FILE, GET_FILES_LIST, GET_FILE, CHOOSE_BUTTON, NOT_COMPLETED, // id014_QuestionTask
    CHOOSE_POSITION, CHOOSE_DEPARTMENT, STAFF_DEPART, STAFF_BACK_BUTTON, DEP_BACK_BUTTON,//id018_ShowStaffInfo
    CHOOSE_EMPLOYEE, //id019_AddCategoryForEmployee
    EDITION, NEW_CATEGORY,UPDATE_CATEGORY,CHOOSE_CATEGORY, SET_TEXT_KZ,//id020_EditorEmployee
    CHOOSE_STAFF, CHOOSE_STAFF_OF_DEPARTMENT, STAFF_UPDATE_PHOTO, STAFF_UPDATE_TEXT, DEP_UPDATE_PHOTO, DEP_UPDATE_TEXT,//id021_EditorSpecial

}
