package baliviya.com.github.eduBot.entity.enums;

public enum WaitingType {

    START,
    SET_FULL_NAME, SET_PHONE_NUMBER,  // id003_Registration
    CHOICE_CATEGORY, HANDLING_TEXT, // id004_Task
    CHOICE_RECEPTION, SET_QUESTION,
    WAIT, EVENT_SELECTION, EVENT,
    QUEST,
    START_DATE, END_DATE,
    CHOICE_OPTION,
    SET_TEXT,
    DONE, CHOICE_APPEAL, BACK_BUTTON_IN_MENU,
    CHOOSE_EVENT, NEW_EVENT, SET_PHOTO, SET_TEXT_EVENT, CHOOSE_OPTION, DONE_BUTTON, COMMAND_EDITOR, NEXT_KEYBOARD, UPDATE_BUTTON, UPDATE_TEXT, UPDATE_FILE, UPDATE_BUTTON_LINK, NOT_COMPLETED, // id014_QuestionTask
    CHOOSE_POSITION, CHOOSE_DEPARTMENT, STAFF_DEPART, BACK_BUTTON, BACK_BUTTON01//id018_ShowStaffInfo
}
